config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'root#index'

  resources :users, only: [:show, :profile] do
    resources :shelves, only: [:create, :show] do
      resources :comments, only: [:create]
    end
    collection do
      get '/:id/profile', to: 'users#profile', as: 'profile'
    end
  end

  resources :books, only: [:show, :new, :create] do
    collection do
      get 'search_result'
    end
  end

  resources :book_shelves, only: [:create, :destroy]
  resources :reviews, only: [:create, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :shelves, through: :book_shelves
  has_many :book_shelves
  has_many :reviews
end

app/models/book_shelf.rb
class BookShelf < ApplicationRecord
  belongs_to :book
  belongs_to :shelf
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :shelf
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
  belongs_to :shelf
end

app/models/shelf.rb
class Shelf < ApplicationRecord
  belongs_to :user
  has_many  :reviews
  has_many :books, through: :book_shelves
  has_many :book_shelves
  has_many :comments
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :reviews
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :shelf
  has_many :reviews
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :create_shelf

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    devise_parameter_sanitizer.permit(:account_update, keys:[:name, :image])
  end

  private
  def create_shelf
    if user_signed_in? && !(current_user.shelf)
      Shelf.create(name: current_user.name + "の本棚", user_id: current_user.id)
    end
  end
end

app/controllers/book_shelves_controller.rb
class BookShelvesController < ApplicationController
  before_action :set_current_user_shelf
  def create
    @book_shelf = BookShelf.create(book_id: params[:book_id], shelf_id: @shelf.id)
  end

  def destroy
    if @book_shelf = BookShelf.find_by(book_id: params[:book_id], shelf_id: @shelf.id)
      @book_shelf.delete
    else
      @book_shelf = BookShelf.find(params[:id])
      @book = @book_shelf.book
      @shelf = @book_shelf.shelf
      @review = Review.find_by(book_id: @book.id, shelf_id: @shelf.id)
      @book_shelf.delete
      @review.delete
      redirect_to book_path(@review.book)
    end
  end

  private
    def set_current_user_shelf
      @shelf = current_user.shelf
    end

    def book_shelf_params
      params.permit(:user_id)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
    @reviews = @book.reviews.order("created_at DESC")
    if user_signed_in?
      @shelf = current_user.shelf
      if @book.reviews.find_by(user_id: current_user.id)
        @review = Review.find_by(book_id: @book.id, user_id: current_user.id)
      end
    end
  end

  def search_result
    if user_signed_in?
      @shelf = current_user.shelf
      @user_books = @shelf.books
    end
    @search_word = params[:info]
    @books = Book.where('title LIKE(?) OR author LIKE(?)', "%#{params[:info]}%", "#{params[:info]}%").page(params[:page]).per(10)
  end

  def new
    @book = Book.new
  end

  def create
    Book.create(book_params)
  end

  private
  def set_current_shelf
    @shelf = current_user.shelf
  end

  def book_params
    params.require(:book).permit(:title, :author, :publisher, :image, :release_year, :release_month, :release_day, :price)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment =Comment.create(text: params[:comment][:text], shelf_id: params[:shelf_id], user_id: current_user.id)
    if @comment.save
       flash[:success] = "コメントを投稿しました。"
      redirect_to :back
    else
      flash.now[:alert] = "メッセージを入力してください。"
      redirect_to :back
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.create(book_id: params[:book_id], user_id: current_user.id, shelf_id: current_user.shelf.id)
    respond_to do |format|
      format.json { render 'create', handlers: 'jbuilder' }
    end
  end

  def destroy
    @review = Review.find_by(book_id: params[:book_id], shelf_id: current_user.shelf.id)
    @review.delete
  end

  def edit
    @review = Review.find(params[:id])
    @book = @review.book
    @shelf = current_user.shelf
    @book_shelf = BookShelf.find_by(book_id: @book.id, shelf_id: @shelf.id)

  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    if @review.save
      respond_to do |format|
        format.html { redirect_to book_path(@review.book) }
        format.json
      end
    end
  end

  def review_params
    params.require(:review).permit(:text)
  end

end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController
  def show
    @user = User.find(params[:id])
    @shelf = @user.shelf
    @comment = Comment.new
    @comments = @shelf.comments.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :profile]

  def show
    @shelf = @user.shelf
    @books = @shelf.books
  end

  def profile
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.haml
.container
  .left-content
    %p.root-path
      = link_to "ブクログ ", root_path, class: "text-link"
      > キーワードで検索(link:仮) > 検索ワード(仮)
    %h1.search-heading
      本の検索
    #books-search
      %input.book--search--field.book--search{:name => "name", :placeholder => "仮置き", :type => "text"}
      %a.fa.fa-search.book-search-btn
    %p.serch-introduction
      まずは商品名、著者名、出版社名などを入力して検索してください。</br>
      例えば...梅沢富美男や 梅沢富美男や 梅沢富美男など。
    %h3.t10M
      梅澤富美男(仮)の作品ランキング・新刊情報・電子書籍
    .item-unit
      %ul.units
        %li.unit
          おすすめ順
        %li.unit
          人気順
        %li.unit
          レビュー数順
        %li.unit
          新刊情報
        %li.unit
          電子書籍
        %li
          ※準備中
    .edit-list
      - @books.each do |book|
        %table.tabletype-edit
          %tbody
            %tr.td-item
              %td.td-info
                .book-prof
                  %h3.book-title
                    = book.title
                  .agregate
                    %span.btn-users
                      260人が登録(仮)
                    %span.btn-rating
                      ★4.21(仮)
                    %span.btn-reviews
                      10レビュー(仮)
                  .desc-mini
                    %p.book-info.book-author
                      = book.author + " /  本(仮) / " + book.release_year.to_s + "年" + book.release_month.to_s + "月" + book.release_day.to_s + "日 /  ¥ " + book.price.to_s
            %tr.book-registration
              %td.book-cover
                = image_tag(book.image, alt: "?", class: "book-image")
              %td.desc
                + 本棚に登録
    = paginate(@books)
  .right-content

app/views/books/new.html.haml
.container
  .left-content
    %p.root-path
      本の登録画面
      = form_for @book, class: "book-registration-form" do |f|
        .category
          = f.label :title
          = f.text_field :title, autofocus: true
        .category
          = f.label :author
          = f.text_field :author
        .category
          = f.label :publisher
          = f.text_field :publisher
        .category
          = f.label :image
          = f.text_field :image
        .category
          = f.label :release_year
          = f.text_field :release_year
        .category
          = f.label :release_month
          = f.text_field :release_month
        .category
          = f.label :release_day
          = f.text_field :release_day
        .category
          = f.label :price
          = f.text_field :price
        = f.submit "登録"

app/views/books/search_result.html.haml
.container
  .left-content
    %p.root-path
      = link_to "ブクログ ", root_path, class: "text-link", data: {"turbolinks" => false}
      > キーワードで検索(link:仮) > 検索ワード(仮)
    %h1.search-heading
      本の検索
    #books-search
      = form_tag(search_result_books_path, method: :get) do
        = text_field_tag :info, params[:info], class: "book--search", placeholder: "作品・著者名で検索して本棚登録"
        = submit_tag '', class: "book-search-btn", id: 'book-search-btn-body',style: "display:none;"
      %a.fa.fa-search#book-search--body
    %p.serch-introduction
      まずは商品名、著者名、出版社名などを入力して検索してください。</br>
      例えば...梅沢富美男や 梅沢富美男や 梅沢富美男など。
    %h3.t10M
      = @search_word + "の作品ランキング・新刊情報・電子書籍"
    .item-unit
      %ul.units
        %li.unit
          おすすめ順
        %li.unit
          人気順
        %li.unit
          レビュー数順
        %li.unit
          新刊情報
        %li.unit
          電子書籍
        %li
          ※準備中
    .edit-list
      - @books.each do |book|
        %table.tabletype-edit{data: {id: book.id, title: book.title}}
          %tbody#book-information-area
            %tr.td-item
              %td.td-info
                .book-prof
                  .delete-btn-area
                    - if user_signed_in?
                      - if @user_books.include?(book)
                        %span.book-delete-btn
                          ✕
                  %h3.book-title
                    = link_to book_path(book), class: "book-title-link", data: {"turbolinks" => false} do
                      = book.title
                  .agregate
                    %span.btn-users
                      = book.shelves.length.to_s + "人が登録"
                    / %span.btn-rating
                    /   ★3.20(仮)
                    %span.btn-reviews
                      = book.reviews.where.not(text: blank?).count.to_s + "レビュー"
                  .desc-mini
                    %p.book-info
                      = book.author + " /  本 / " + book.release_year.to_s + "年" + book.release_month.to_s + "月" + book.release_day.to_s + "日 /  ¥ " + book.price.to_s
            %tr.book-registration
              %td.book-cover
                = image_tag(book.image, alt: "?", class: "book-image")
              - if user_signed_in?
                - if @user_books.include?(book)
                  %td.after-add-book-area
                    %ul.edit-tab
                      %li.edit-tab-basic
                        登録情報
                      %li.edit-tab-review
                        レビュー
                    / #edit-area
                    /   .edit-basic-wrapper
                    /     #edit-status-area
                    /       ※準備中
                    .edit-review-wapper
                      = form_for Review.find_by(book_id: book.id, user_id: current_user.id), html: {id: "js-review-form", class: "edit-review-form"} do |f|
                        = f.text_area :text, class: "edit-review-textarea", placeholder: "レビューや感想を書く", rows: "10", cols: "30"
                        .edit-review-btn-area{data: {id: Review.find_by(book_id: book.id, user_id: current_user.id).id}}
                          %span.edit-review-btn#js-review-btn
                            投稿
                - else
                  %td.desc
                    .add-book-area
                      %span.add-book-btn
                        + 本棚に登録
              - else
                %td.desc
                  レビューを見る
    = paginate(@books)
  .right-content

app/views/books/show.html.haml
.container
  .left-content
    %p.root-path
      = link_to "ブクログ ", root_path, class: "text-link", data: {"turbolinks" => false}
      = " > " + @book.title
    .book-info-show-area
      %h1.book-title
        = @book.title
      .book-show-area
        .book-image-area
          .book-image
            = image_tag(@book.image, class: "book-show-image")
          .review-add-shelf
            - if user_signed_in?
              - if @shelf.books.include?(@book)
                = link_to edit_review_path(@review), data: {"turbolinks" => false} do
                  %span.write-review-btn
                    レビューを書く
              - else
                %span.add-shelf-btn{data: {id: @book.id}}
                  + 本棚に登録
            - else
              = link_to new_user_session_path, class: "redirect-sign-in", data: {"turbolinks" => false} do
                %span.add-shelf-btn
                  + 本棚に登録
        .book-info-area
          .book-info-aggregate
            %ul
              %li
                %i.fa.fa-user
                %span.bold
                  = @book.shelves.length
                人登録
              / %li
              /   %i.fa.fa-star
              /   %span.bold
              /     3.20
              /   評価(仮)
              %li
                %i.fa.fa-comment
                %span.bold
                  = @book.reviews.where.not(text: blank?).count
                レビュー
          .book-info-author
            = "著者：" + @book.author
          .book-info-description
            = @book.publisher + " (" + @book.release_year.to_s + "年" + @book.release_month.to_s + "月" + @book.release_day.to_s + "日発売)"
    #review-line
      %h2.under-line
        = @book.title + "の感想・レビュー・評価"
      .review-sort
        %ul
          %li.all-reviews
            ▼全てのレビュー
          %li
            評価★5
          %li
            評価★4
          %li
            評価★3
          %li
            評価★2
          %li
            評価★1 ※仮置き
      %ul.reviews
        - @reviews.each do |review|
          - unless review.text.blank?
            %li.review
              .user-icon-area
                - if review.user.image.blank?
                  = link_to user_path(review.user), data: {"turbolinks" => false} do
                    = image_tag("prof_noimage.gif", class: "review-user-img")
                - else
                  = link_to user_path(review.user), data: {"turbolinks" => false} do
                    = image_tag(review.user.image, class: "review-user-img")
              .summary
                .user-info-area
                  = link_to user_path(review.user), class: "users-page-link", data: {"turbolinks" => false} do
                    = review.user.name + "さん"
                  のレビュー
                .rating-area
                .review-text
                  = simple_format(review.text)
  .right-content

app/views/layouts/_flash.html.haml
.flash-message-area
  - flash.each do |key, value|
    - if key == "success"
      .flash-message-success
        = value

app/views/layouts/_footer.html.haml
%footer.footer-body
  .footer-list
    %h1
      人気の作家
  .footer-list
    %h1
      人気の作品
  .footer-list
  .copyrights
    %p.agreement
      利用規約 | Cookieの使用について | 会社概要 | プライバシーポリシー
    %p.copyright
      Copyright&copy; 2017 SG,inc ALL Rights Reserved.

app/views/layouts/_header.html.haml
%header
  .global-navi.global-navi-login.clearFix
    .global-navi-inner
      .global-navi--left
        = link_to root_path, data: {"turbolinks" => false} do
          - if user_signed_in?
            = image_tag("booklog_top.png", alt: "アイコン", class: "navi-menu top-icon")
          - else
            = image_tag("top-logout.png", alt: "アイコン", class: "navi-menu top-icon")
        %ul.menu--lists
          %li.navi-manu ランキング
          %li.navi-manu 新刊情報
          %li.navi-manu 談話室
          %li.navi-manu まとめ
        = form_tag(search_result_books_path, method: :get) do
          = text_field_tag :info, params[:info], placeholder: "作品・著者名で検索して本棚登録", class: "book--search--field navi-manu"
          = submit_tag '', class: "book-search-btn", id: "book-search-btn-header", style: "display:none;"
          %a.fa.fa-search#book-search--header
          .global-navi--right
            - if user_signed_in?
              - if current_user.image.blank?
                = image_tag("prof_noimage.gif", class: "header-user-iamge")
              - else
                = image_tag(current_user.image, class: "header-user-iamge")
              = link_to new_book_path, data: {"turbolinks" => false} do
                %i.fa.fa-file-o.link-btn
              = link_to profile_users_path(current_user), data: {"turbolinks" => false} do
                %i.fa.fa-home.link-btn
              = link_to user_path(current_user), data: {"turbolinks" => false} do
                %i.fa.fa-book.link-btn
              = link_to "ログアウト", destroy_user_session_path, class: "logout-btn link-btn", data: {"turbolinks" => false}, method: :delete
            - else
              = link_to "新規登録", new_user_registration_path, class: "registration-btn link-btn", data: {"turbolinks" => false}
              = link_to "ログイン", new_user_session_path, class: "login-btn link-btn", data: {"turbolinks" => false}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Booklog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: "layouts/header"
    #contains
      = render partial: "layouts/flash"
      = yield
      = render partial: "layouts/footer"

app/views/reviews/edit.html.haml
.container
  %p.root-path
    = link_to "ブクログ ", root_path, class: "text-link", data: {"turbolinks" => false}
    = " > "
    = link_to @review.book.title, book_path(@book), class: "text-link", data: {"turbolinks" => false}
    = " > " + current_user.name + "さんのレビュー > 登録情報の編集・削除"
  .left-content
    %h1#edit
      登録情報の編集・削除
    .edit-book-area
      .book-image-area
        = image_tag(@book.image, class: "review-edit-book-img")
      .book-info-area
        %h2.book-title
          = link_to book_path(@book), class: "book-title-link", data: {"turbolinks" => false}  do
            = @book.title
        .book-author
          = @book.author
    .tab-menu
      %ul.edit-tabs
        %li.edit-tab-review.active
          レビュー
        / %li.edit-tab.edit-tab-phrase
        /   フレーズ
        / %li.edit-tab.edit-tab-reread
        /   再読記録
        %li.edit-tab.edit-tab-delete
          削除
    #edit_panels.edit-area
      #tab1
        = form_for @review do |f|
          %table
            %tr
              %th
                レビュー・感想
              %td
                .edit-review-area
                  = f.text_area :text, class: "edit-review", placeholder: "レビューや感想を書く", size: "20×10"
          %p.submit
            = f.submit "登録情報を更新する",　class: "review-edit-send-btn", id: "review-send-btn"
      #tab4
        %p#tab4-lead
          このアイテムを本棚から削除します。あなたのレビューや再読記録も削除されますが、フレーズは別途削除が必要です。
          .delete-from-shelf
            = link_to book_shelf_path(@book_shelf), class: "delete-from-shelf-btn", method: :delete, data: {"turbolinks" => false} do
              本棚から削除する
  .right-content

app/views/root/index.html.haml
.container

app/views/shelves/show.html.haml
.container
  .left-content
    %p.root-path
      = link_to "ブクログ ", root_path, class: "text-link link-btn", data: {"turbolinks" => false}
      >
      = link_to @user.name + "さんの本棚", user_path(@user),class: "text-link link-btn", data: {"turbolinks" => false}
      >
      = @user.name + "さんの本棚へのコメント"
    .user-wrapper-profile
      = render partial: "users/info"
    .shlef-comments-area.clearfix
      %ul.comments
        - if @comments.length == 0
          %span.non-comment
            本棚へのコメントはまだありません。
        - else
          %p.comment-lead
            コメント一覧
          - @comments.each do |comment|
            %li.comment
              .user-icon-area
                - if comment.user.image.blank?
                  = link_to user_path(comment.user), data: {"turbolinks" => false} do
                    = image_tag("prof_noimage.gif", class: "comment-user-img")
                - else
                  = link_to user_path(comment.user), data: {"turbolinks" => false} do
                    = image_tag(comment.user.image, class: "comment-user-img")
              .summary
                .user-info-area
                  = link_to user_path(comment.user), class: "users-page-link", data: {"turbolinks" => false} do
                    = comment.user.name + "さん"
                  のコメント
                .comment-text
                  = simple_format(comment.text)
    = paginate(@comments)
    .comment-create-area
      %span.comment-create-area--lead
        本棚へコメント
        = form_for [@user, @shelf, @comment] do |f|
          = f.text_area :text, class: "comment-area",placeholder: "コメントを入力してください"
          .submit-area
            = f.submit "コメントする", class: "comment-btn"
  .right-content

app/views/users/_info.html.haml
.user-prof
  = link_to user_path(@user) do
    - if @user.image.blank?
      = image_tag("prof_noimage.gif", class: "prof-img-m")
    - else
      = image_tag(@user.image, class: "prof-img-m")
  %ul.user-navi
    %li.user-navi-shelf
      %i.fa.fa-book
    %li.user-navi-timeline
      %i.fa.fa-clock-o
    %li.user-navi-user
      %i.fa.fa-user
    %li
      %i.fa.fa-info-circle
.user-shelf
  %h1
    プロフィール
    - if current_user.id == @user.id
      = link_to edit_user_registration_path do
        %i.fa.fa-gear
  %p
    = @user.name + "さん"
  %ul.user-activity
    %li
      %dl
        %dt
          登録アイテム
        %dd
          = @user.shelf.books.length
    %li.list-border-left
      %dl
        %dt
          レビュー
        %dd
          = @user.reviews.where.not(text: blank?).count
    %li.list-border-left
      %dl
        %dt
          レビュー率
        %dd
          0.0% (仮)
    - if current_user.id == @user.id
      %li.list-border-left
        %dl
          %dt
            フレーズ
          %dd
            0 (仮)
  .user-social
    .user-follow-btn
      - if current_user.id == @user.id
        %span.follow-myself
          あなたの本棚
      - else
        %span.follow-btn
          ♥ フォロー
    %ul.user-friends
      %li.follow
        0フォロー
      %li.follower
        0フォロワー※仮置き
    .shelf-comments-link-area
      = link_to user_shelf_path(@user), class: "shelf-comments-link" do
        = "本棚へのコメント(" + @user.shelf.comments.length.to_s + ")"

app/views/users/profile.html.haml
.container
  .left-content
    %p.root-path
      = link_to "ブクログ ", root_path, class: "text-link link-btn"
      >
      = link_to @user.shelf.name, user_path(@user), class: "text-link link-btn"
      > プロフィール
    .user-wrapper-profile
      = render partial: "info"
    %p.lead
      1993年9月1日生まれの男性(仮)
    %table.prof-table
      %tr
        %td.prof-item
          名前
        %td.prof-info
          = @user.name
      %tr
        %td.prof-item
          本棚の名前
        %td.prof-info
          = link_to @user.shelf.name, user_path(@user), class: "text-link"
      %tr
        %td.prof-item
          本棚の紹介文
        %td.prof-info
          良いです(仮)
      %tr
        %td.prof-item
          性別
        %td.prof-info
          男性(仮)
      %tr
        %td.prof-item
          生年月日
        %td.prof-info
          1993年 09月 01月生まれ(仮)
    %ul.prof-lists
      %li.prof-list
        プロフィール
      %li.prof-data
        自己紹介を書く
      %li.prof-list
        パーソナルタグ
      %li.prof-data
        パーソナルタグを設定する
      %li.prof-list
        興味のあるジャンル
      %li.prof-data
        興味のあるジャンルを設定する
      %li.prof-list
        好きな作家など
      %li.prof-data
        好きな作家を設定する
      %li.prof-list
        お気に入りベスト3
      %li.prof-data
        %table.favorite-three
          %tr
            %td.favorite-rank.favorite-rank-1
              1
            %td.favorite-data
              設定
            %td.favorite-rank.favorite-rank-2
              2
            %td.favorite-data
              設定
            %td.favorite-rank.favorite-rank-3
              3
            %td.favorite-data
              設定
      %li.prof-list
        読書目標
      %li.prof-data.last-line
        読書目標を設定する
  .right-content

app/views/users/show.html.haml
.container-02
  #users-header-profile-wrapper
    #users-header-profile
      #user-header-profile
        %p.root-path
          = link_to "ブクログ ", root_path, class: "text-link link-btn"
          = " > " + @user.name + "さんの本棚"
        .user-wrapper-shelf
          = render partial: "info"
    .shelf-header
      .shelf-header-menu
    #shelf.shelf-front-area
      .shelf-area
        - @books.each do |book|
          .book-area
            = image_tag(book.image, alt: "?", class: "book-covar-image")